// Generated by build/write_buildflag_header.py
// From "//base:debugging_flags"

#ifndef BASE_DEBUG_DEBUGGING_FLAGS_H_
#define BASE_DEBUG_DEBUGGING_FLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_ENABLE_PROFILING() (0)
#define BUILDFLAG_INTERNAL_ENABLE_MEMORY_TASK_PROFILER() (0)
#define BUILDFLAG_INTERNAL_CAN_UNWIND_WITH_FRAME_POINTERS() (0)

#endif  // BASE_DEBUG_DEBUGGING_FLAGS_H_
